
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: true
      # Build Docker image
    - name: Build Docker
      run: mvn jib:build
    - name: send custom message
      uses: Lukasss93/telegram-action@v2
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_TO }}
        message: |
              The ${{ github.event_name }} event triggered final step.
              echo This event is a pull request that had an assignee removed and message should be changed.
